name: Default

on: [push]

jobs:
  setup-linux:
    name: Setup - Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
  test-jest:
    name: Test - Jest
    runs-on: ubuntu-latest
    needs: setup-linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - uses: actions/cache@v1
        id: submodule-cache
        with:
          path: src/shared/node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('src/shared/yarn.lock') }}
      - name: Test
        run: yarn test --watchAll=false --ci --runInBand